version: '3.8'

services:
  # 前端应用服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zhongyue-frontend
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - web_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # API服务
  api:
    container_name: zhongyue-nodejs-api-dev
    build:
      context: ../zhongyue-nodejs # 调整为后端API项目的相对路径
      dockerfile: Dockerfile.dev
    volumes:
      - ../zhongyue-nodejs:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: pnpm run start:dev
    env_file:
      - ../zhongyue-nodejs/.env # 调整为后端API项目的环境变量文件路径
    networks:
      - web_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:3000/api/health']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  # 数据库服务（如果有数据库，取消注释此部分）
  # db:
  #   image: postgres:13-alpine
  #   container_name: zhongyue-db
  #   restart: unless-stopped
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=zhongyue
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - zhongyue-network

networks:
  web_network:
    driver: bridge
# 如果有数据库，取消注释此部分
# volumes:
#   pgdata:
