version: '3.8'

services:
  # 前端应用服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zhongyue-frontend
    ports:
      - '8888:80'
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - web_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # API服务
  api:
    container_name: zhongyue-nodejs-api-prod
    build:
      context: ../zhongyue-nodejs
      dockerfile: ../zhongyue-nodejs/Dockerfile
      target: production
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - ../zhongyue-nodejs/.env
    networks:
      - web_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  # 数据库服务（如果有数据库，取消注释此部分）
  # db:
  #   image: postgres:13-alpine
  #   container_name: zhongyue-db
  #   restart: unless-stopped
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=zhongyue
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - zhongyue-network

networks:
  web_network:
    driver: bridge
    external: true
# 如果有数据库，取消注释此部分
# volumes:
#   pgdata:
